version: "3.8"
services:
  menu-service:
    image: "menu-service"
    container_name: "menu-service"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9091:9091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/menu_service_db

  postgres:
    image: "postgres:16.1"
    container_name: "postgres_1"
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbusb:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "menu_service_db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  dbusb:
    driver: local